const root = document.documentElement;
const pages = [...document.querySelectorAll('.page')], nav = document.getElementById('siteNav'), footer = document.getElementById('siteFooter'), mobileMenu = document.getElementById('mobileMenu'), hamb = document.getElementById('hambBtn');
function closeMenu() { if (mobileMenu) { mobileMenu.classList.remove('open'); } if (hamb) { hamb.setAttribute('aria-expanded', 'false'); hamb.innerHTML = '<i class="fa-solid fa-bars"></i>' } }
function initReveal() { const active = document.querySelector('.page.active'); if (!active) return; const els = active.querySelectorAll('.reveal'); if (!('IntersectionObserver' in window)) { els.forEach(e => e.classList.add('visible')); return } const io = new IntersectionObserver(es => es.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); io.unobserve(e.target) } }), { threshold: .08 }); els.forEach(e => io.observe(e)) }
function dashboardViewFromHash() { const raw = location.hash.slice(1) || 'home1'; if (!raw.startsWith('dashboard')) return 'overview'; const part = raw.split('/')[1] || 'overview'; return ['overview', 'chargers', 'session', 'history', 'payments', 'billing', 'profile'].includes(part) ? part : 'overview' }
function setDashboardView(view, updateHash = false) { const valid = ['overview', 'chargers', 'session', 'history', 'payments', 'billing', 'profile']; if (!valid.includes(view)) view = 'overview'; document.querySelectorAll('.dash-page').forEach(p => p.classList.toggle('active', p.dataset.dashPage === view)); document.querySelectorAll('.dash-side-nav a').forEach(a => a.classList.toggle('active', a.dataset.dashView === view)); document.documentElement.className = document.documentElement.className.replace(/\broute-(?:dashboard|overview|chargers|session|history|payments|billing|profile)\b/g, '').trim(); document.documentElement.classList.add('route-dashboard', 'route-' + view); if (updateHash) { history.pushState(null, '', view === 'overview' ? '#dashboard' : '#dashboard/' + view) } if (window.innerWidth <= 1000) closeDashMenu(); setTimeout(initReveal, 20) }
function closeDashMenu() { document.getElementById('dashSidebar')?.classList.remove('open'); document.getElementById('dashOverlay')?.classList.remove('open'); document.getElementById('dashHamb')?.setAttribute('aria-expanded', 'false'); const b = document.getElementById('dashHamb'); if (b) b.innerHTML = '<i class="fa-solid fa-bars"></i>' }
function openDashMenu() { document.getElementById('dashSidebar')?.classList.add('open'); document.getElementById('dashOverlay')?.classList.add('open'); document.getElementById('dashHamb')?.setAttribute('aria-expanded', 'true'); const b = document.getElementById('dashHamb'); if (b) b.innerHTML = '<i class="fa-solid fa-xmark"></i>' }
function showPage() { let raw = location.hash.slice(1); let id = raw ? raw.split('/')[0] : ''; if (!id || !document.getElementById(id)) { id = document.getElementById('home1') ? 'home1' : (pages.length > 0 ? pages[0].id : ''); } if (id) pages.forEach(p => p.classList.toggle('active', p.id === id)); const privatePage = id === 'login' || id === 'dashboard'; nav?.classList.toggle('hide', privatePage); footer?.classList.toggle('hide', privatePage); closeMenu(); if (id === 'dashboard') setDashboardView(dashboardViewFromHash()); else { closeDashMenu(); document.documentElement.className = document.documentElement.className.replace(/\broute-(?:dashboard|overview|chargers|session|history|payments|billing|profile)\b/g, '').trim() } window.scrollTo({ top: 0, behavior: 'instant' }); setTimeout(initReveal, 30); document.title = id === 'dashboard' ? 'VoltGrid — Driver Dashboard' : id === 'login' ? 'VoltGrid — Driver Login' : id === 'network' ? 'VoltGrid — Charging Network' : 'VoltGrid — Public EV Charging Network' }
window.addEventListener('hashchange', showPage); showPage();
document.querySelectorAll('.brand[href="#home1"],.auth-logo-link').forEach(a => a.addEventListener('click', e => { e.preventDefault(); if (location.hash === '#home1') { showPage() } else { location.hash = '#home1' } }));

function updateThemeIcons() { const dark = root.dataset.theme === 'dark'; const icon = dark ? 'fa-sun' : 'fa-moon'; document.getElementById('themeBtn') && (document.getElementById('themeBtn').innerHTML = '<i class="fa-solid ' + icon + '"></i>'); document.getElementById('mobileTheme') && (document.getElementById('mobileTheme').innerHTML = '<i class="fa-solid ' + icon + '"></i> Theme'); document.getElementById('dashThemeBtn') && (document.getElementById('dashThemeBtn').innerHTML = '<i class="fa-solid ' + icon + '"></i><span>Theme</span>'); document.getElementById('authTheme') && (document.getElementById('authTheme').innerHTML = '<i class="fa-solid ' + icon + '"></i>') }
function setTheme(t) { root.dataset.theme = t; localStorage.setItem('voltgrid-theme', t); updateThemeIcons() }
setTheme(localStorage.getItem('voltgrid-theme') || 'light');
document.getElementById('themeBtn') && (document.getElementById('themeBtn').onclick = () => setTheme(root.dataset.theme === 'dark' ? 'light' : 'dark')); document.getElementById('mobileTheme') && (document.getElementById('mobileTheme').onclick = () => setTheme(root.dataset.theme === 'dark' ? 'light' : 'dark')); document.getElementById('dashThemeBtn') && (document.getElementById('dashThemeBtn').onclick = () => setTheme(root.dataset.theme === 'dark' ? 'light' : 'dark')); document.getElementById('authTheme') && (document.getElementById('authTheme').onclick = () => setTheme(root.dataset.theme === 'dark' ? 'light' : 'dark'));
function toggleRTL() { const d = root.getAttribute('dir') === 'rtl' ? 'ltr' : 'rtl'; root.setAttribute('dir', d); localStorage.setItem('voltgrid-dir', d) } root.setAttribute('dir', localStorage.getItem('voltgrid-dir') || 'ltr'); document.getElementById('rtlBtn') && (document.getElementById('rtlBtn').onclick = toggleRTL); document.getElementById('mobileRTL') && (document.getElementById('mobileRTL').onclick = toggleRTL); document.getElementById('dashRTLBtn') && (document.getElementById('dashRTLBtn').onclick = toggleRTL); document.getElementById('authRTL') && (document.getElementById('authRTL').onclick = toggleRTL);
if (hamb) { hamb.onclick = () => { const open = mobileMenu.classList.toggle('open'); hamb.setAttribute('aria-expanded', open); hamb.innerHTML = open ? '<i class="fa-solid fa-xmark"></i>' : '<i class="fa-solid fa-bars"></i>' } } document.querySelectorAll('.mobile-menu a').forEach(a => a.onclick = closeMenu);
window.addEventListener('scroll', () => document.getElementById('topBtn')?.classList.toggle('show', scrollY > 450)); document.getElementById('topBtn') && (document.getElementById('topBtn').onclick = () => scrollTo({ top: 0, behavior: 'smooth' }));
document.getElementById('contactForm') && (document.getElementById('contactForm').onsubmit = e => { e.preventDefault(); document.getElementById('formMsg').classList.remove('hide'); e.target.reset() });
document.getElementById('loginForm') && (document.getElementById('loginForm').onsubmit = e => { e.preventDefault(); location.hash = '#dashboard' }); document.getElementById('registerForm') && (document.getElementById('registerForm').onsubmit = e => { e.preventDefault(); alert('Demo account created. You can now log in.'); document.getElementById('authCard').classList.remove('registering') });
const authCard = document.getElementById('authCard'); document.getElementById('showRegister')?.addEventListener('click', e => { e.preventDefault(); authCard.classList.add('registering') }); document.getElementById('showLogin')?.addEventListener('click', e => { e.preventDefault(); authCard.classList.remove('registering') });
function startDemo(station) { alert('Demo: ' + station + ' selected. In production this would authorize and start the charging session.'); }
document.querySelectorAll('.dash-side-nav a').forEach(a => a.addEventListener('click', e => { e.preventDefault(); const href = a.getAttribute('href') || '#dashboard'; const view = href.split('/')[1] || 'overview'; setDashboardView(view, true) }));
document.getElementById('dashHamb')?.addEventListener('click', () => { document.getElementById('dashSidebar').classList.contains('open') ? closeDashMenu() : openDashMenu() }); document.getElementById('dashOverlay')?.addEventListener('click', closeDashMenu); document.getElementById('dashLogout')?.addEventListener('click', () => { closeDashMenu(); location.hash = '#login' });